-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Eva_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Eva_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Eva_db` DEFAULT CHARACTER SET utf8 ;
USE `Eva_db` ;

-- -----------------------------------------------------
-- Table `Eva_db`.`label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Eva_db`.`label` (
  `Lbltitle` VARCHAR(15) NOT NULL,
  `Lblstreet` VARCHAR(25) NULL,
  `Lblcity` VARCHAR(20) NULL,
  `Lblstate` VARCHAR(20) NULL,
  `Lblpostcode` VARCHAR(10) NULL,
  `Lblnation` VARCHAR(20) NULL,
  PRIMARY KEY (`Lbltitle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Eva_db`.`cd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Eva_db`.`cd` (
  `Cdid` INT(10) NOT NULL,
  `Cdlblid` VARCHAR(10) NULL,
  `Cdtitle` VARCHAR(25) NULL,
  `Cdyear` YEAR NULL,
  `Lbltitle` VARCHAR(15) NULL,
  PRIMARY KEY (`Cdid`),
  INDEX `Lbltitle_idx` (`Lbltitle` ASC),
  CONSTRAINT `Lbltitle`
    FOREIGN KEY (`Lbltitle`)
    REFERENCES `Eva_db`.`label` (`Lbltitle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Eva_db`.`track`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Eva_db`.`track` (
  `Trkid` INT(11) NOT NULL,
  `Trknum` INT(11) NULL,
  `Trktitle` VARCHAR(25) NULL,
  `Trklength` DECIMAL(4,2) NULL,
  `Cdid` INT(11) NULL,
  PRIMARY KEY (`Trkid`),
  INDEX `Cdid_idx` (`Cdid` ASC),
  CONSTRAINT `Cdid`
    FOREIGN KEY (`Cdid`)
    REFERENCES `Eva_db`.`cd` (`Cdid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
